In [12]:
import cv2
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"
import numpy as np
import random

import torch

import sys
sys.path.append('../')
print(sys.path)

np.random.seed(32635)

['/home/hkhachatrian/mae/jupyter_notebooks', '/home/hkhachatrian/miniconda3/lib/python310.zip', '/home/hkhachatrian/miniconda3/lib/python3.10', '/home/hkhachatrian/miniconda3/lib/python3.10/lib-dynload', '', '/home/hkhachatrian/mae/.venv/lib/python3.10/site-packages', '../', '../']


In [2]:
def get_images_for_collage(train_annotation_file, val_annotaion_file, images_folder, images_per_collage=6):

    train_annotation_images = np.load(train_annotation_file, allow_pickle=True).item()['images']
    val_annotation_images = np.load(val_annotaion_file, allow_pickle=True).item()['images']

    train_samples = random.sample(list(enumerate(train_annotation_images)), images_per_collage)
    val_samples = random.sample(list(enumerate(val_annotation_images)), images_per_collage)

    train_indexes = []
    train_image_names = []
    for train_sample in train_samples:
        train_indexes.append(train_sample[0])
        train_image_names.append(images_folder+'train/images/'+train_sample[1]['file_name'])

    val_indexes = []
    val_image_names = []
    for val_sample in val_samples:
        val_indexes.append(val_sample[0])
        val_image_names.append(images_folder+'val/images/'+val_sample[1]['file_name'])

    return train_indexes, train_image_names, val_indexes, val_image_names


In [3]:
def get_collage(image_names, which_part):
    collage_columns = 2
    collage_rows = 3
    columns = []
    for i in range(collage_rows):
        images_in_row = image_names[i*collage_columns:(i+1)*collage_columns]
        rows = []
        for img in images_in_row:
            rows.append(cv2.resize(cv2.imread(img),(224, 224), interpolation=cv2.INTER_NEAREST_EXACT))
        row_image = np.hstack(rows)
        columns.append(row_image)
    collage = np.vstack(columns)
    cv2.imwrite(f'8shot_collage_{which_part}.png', collage)

In [92]:
def create_collage(train_annotation_file, val_annotaion_file, images_folder):
    train_indexes, train_image_names, val_indexes, val_image_names = \
        get_images_for_collage(train_annotation_file, val_annotaion_file, images_folder)

    get_collage(train_image_names, 'train')
    get_collage(val_image_names, 'val')
    return train_indexes, val_indexes

In [5]:
train_annotation_file = '../images/f1m/250_8shot/train/train.npy'
val_annotation_file = '../images/f1m/250_8shot/val/val.npy'
images_folder = '../images/f1m/250_8shot/'

In [6]:
knn_distances = '../embeddings/fair1m/predictions_knn/dino_train_8_val_8/dino_train_8_val_80_7840.npy'

In [30]:
knn_folder = '../embeddings/fair1m/predictions_knn/dino_train_8_val_8/'

In [13]:
good_values = np.load(knn_distances, allow_pickle=True).item()['good_values']

In [25]:
good_indexes = np.load(knn_distances, allow_pickle=True).item()['good_indices']

In [26]:
for k in enumerate(good_indexes):
    print(k)

(0, array([2360, 7266, 1759, 1805,  852, 7379, 1819, 2218, 7392, 2226]))
(1, array([ 741, 6254, 2386, 2199, 7382, 6270, 7406, 2370, 3533,  432]))
(2, array([2386,  852, 3054, 1009, 3533, 1442, 2228,  394,    8,    1]))
(3, array([ 955,  893, 2383, 1009, 1442,  852,  420, 7669,  892,    1]))
(4, array([ 459, 1345,  942,  981,  893, 1290, 1317,  452,  969, 1456]))
(5, array([ 802, 1372,  840, 2158,  789, 7334,  537, 7263, 1459, 7333]))
(6, array([1372,  802, 1380, 1377, 7391, 1373,  803,  791, 2158, 1378]))
(7, array([ 791, 1380,  792, 1374, 5896,  816,  829, 1373,  856,  861]))
(8, array([1380,  792, 1374,  791,  861, 1373,  794, 1982,  832,  793]))
(9, array([1374, 1380,  791, 1373, 5887,  832,  792, 5890,  861, 1982]))
(10, array([1374, 1373, 1380, 1973, 1386, 1982, 1432, 1387,  832, 1987]))
(11, array([1387, 1374, 3355, 1380, 3735, 1377, 1376, 3733, 1373, 1987]))
(12, array([1422, 5946, 1375,  513,  544, 1398, 1400, 1397, 1378, 1381]))
(13, array([1377, 1398, 3735, 1380, 3733, 7349, 

(6328, array([6926, 6896, 6928, 6098, 6290, 4419, 7410, 5358, 6131, 6291]))
(6329, array([6896, 6291, 6099, 5429, 6919, 2240, 6304, 6974, 4419, 7410]))
(6330, array([6953, 6949, 5357, 6935, 5452, 6966, 5191, 7349, 6934, 5401]))
(6331, array([5340, 5357, 6934, 6935, 4840, 7442,  532, 4771, 6288, 6123]))
(6332, array([6934, 6919, 6933, 6947, 6926, 5351, 6961, 4501, 6974, 5324]))
(6333, array([3307, 4488, 6914, 4490, 6919, 4564, 4502, 3308, 7721, 7720]))
(6334, array([6764, 6939, 6789, 6783, 6966, 3922, 2679, 6786, 6095,  527]))
(6335, array([ 221, 5574, 2242, 5596, 3369, 6731, 6787,  478,  479, 6707]))
(6336, array([ 221, 6731, 2242, 5574, 5596, 7036, 6787, 3369,  478, 4033]))
(6337, array([6779, 2251, 6776, 6789,  198, 3618,  197, 4684, 6738, 7387]))
(6338, array([ 305, 5199, 6781,  198, 7387, 3458, 7365, 3168,  763, 7354]))
(6339, array([3170, 3155, 3171, 6753, 6767, 6766, 6782, 3156, 6302, 3137]))
(6340, array([3736, 3758, 5743, 3691, 3692, 2245, 3746, 6998, 2219, 3705]))
(6341, array

In [22]:
topk_indices = torch.tensor(good_values).topk(k=1, largest=True)

In [23]:
topk_indices

tensor([[1936.8919],
        [1843.5469],
        [1907.6480],
        ...,
        [2661.3187],
        [2338.5419],
        [2413.9101]], dtype=torch.float64)

In [11]:
7840/196

40.0

In [58]:
def compute_1NN(path_to_knn, train_labels):
    k=1
    top_k_classes = []
    top_k_values = []
    top_k_indices = []
    test_indices = []
    
    name_to_chunk = {}
    for chunk_file in os.listdir(path_to_knn):
        chunk = int(chunk_file.split('_')[-1].split('.')[0])
        name_to_chunk[chunk] = chunk_file
    
    for _, knn_file in sorted(name_to_chunk.items()):
        knn = np.load(os.path.join(path_to_knn, knn_file), allow_pickle=True).item()
        chunk_good_values = torch.tensor(knn['good_values'])
        chunk_good_indices = torch.tensor(knn['good_indices'])
        
        topk_indices = chunk_good_values.topk(k=k, largest=True).indices
        topk_labels = torch.zeros_like(topk_indices)
        
        j=0
        for ind, good_index, good_value in zip(topk_indices, enumerate(chunk_good_indices), chunk_good_values):
            test_indices.append(good_index[0])
            real_index = good_index[1][ind]
            top_k_indices.append(real_index.item())
            top_k_values.append(good_value[ind].item())

            topk_labels[j] = train_labels[real_index]
            j+=1
    
        top_k_classes.append(topk_labels)
        
    top_k_classes = torch.cat(top_k_classes)
    
    return top_k_classes, test_indices, top_k_indices, top_k_values

In [59]:
_, test_ind, top_k_ind, top_k_value = compute_1NN(knn_folder, train_labels)

In [40]:
train_labels = torch.tensor(np.load('/home/hkhachatrian/mae/embeddings/fair1m/f1m_dino_8shot_labels_train.npy', allow_pickle=True)).to(device='cpu', dtype=torch.int64)

In [44]:
(7838+1)/196

39.994897959183675

In [51]:
len(test_ind)

7840

In [60]:
top_k_value[0]

1936.891931259648

In [54]:
np.unique(top_k_ind).shape

(3051,)

In [74]:
dist_dict = {}

for i in range(len(top_k_ind)):
    if top_k_ind[i] in dist_dict:
        dist_dict[top_k_ind[i]].append([top_k_value[i], test_ind[i]])
    else:
        dist_dict[top_k_ind[i]] = [[top_k_value[i], test_ind[i]]]

In [76]:
dist_dict

{2360: [[1936.891931259648, 0]],
 741: [[1843.5469245412019, 1]],
 2386: [[1907.6479863116526, 2], [1725.9627954674168, 4870]],
 955: [[2047.7504147221828, 3],
  [1684.6645885415687, 134],
  [2440.7424184652145, 1271],
  [2118.3645330053278, 5103],
  [2131.0103678222536, 5104],
  [2376.2481830961974, 5258]],
 459: [[1704.9669050257285, 4], [1753.6182029889683, 974]],
 802: [[2105.825860538721, 5]],
 1372: [[2225.5125967604467, 6], [1927.8144875721339, 6076]],
 791: [[2015.3038566821735, 7], [2297.8372740390073, 1195]],
 1380: [[2118.2780209037724, 8],
  [1989.9351544217275, 67],
  [2341.3906548616546, 338],
  [2549.0328426723286, 439],
  [2468.099433784289, 440],
  [2458.2987361441715, 468],
  [2322.7302470645163, 509],
  [2337.522966358887, 510],
  [2399.994162779153, 610],
  [2037.5638561379299, 793],
  [2237.9754878496133, 794],
  [2242.800911403461, 842],
  [2163.387665426466, 874],
  [1979.1245130368764, 898],
  [2234.8822850194524, 1197],
  [2181.0573285186397, 1239],
  [2322.343

In [71]:
dist_dict[0]

KeyError: 0

In [78]:
train_labels[6*196:7*196].shape

torch.Size([196])

In [87]:
for j in range(6*196, 7*196):
    if j in dist_dict:
        print(j)
        print(dist_dict[j])

1177
[[1736.42004239441, 3530]]
1178
[[1931.376015633171, 2407], [2157.03076996462, 2700]]
1180
[[2059.7942246073003, 7646]]
1181
[[1974.1926917015999, 2752], [2025.807239550501, 2783]]
1186
[[1598.7429515650308, 102]]
1188
[[1843.9595654478596, 6087]]
1189
[[1638.9636491829388, 1375]]
1190
[[1912.2341562396382, 5306], [1942.0970691432212, 5323]]
1191
[[2108.6311599995915, 7652]]
1193
[[2173.71486409604, 7689]]
1199
[[1987.277707528134, 7498], [1893.7310536679686, 7511], [1948.2169946358943, 7682]]
1200
[[2071.795214572386, 2746]]
1208
[[2150.2378276828263, 1464]]
1209
[[1925.284495168648, 7549], [2052.2515898088786, 7576]]
1212
[[1910.0182463488811, 5895]]
1216
[[2074.3299817446677, 113], [1831.0438539684283, 6086], [2319.9347028301504, 6117]]
1217
[[1810.7162414053073, 2744]]
1218
[[2258.77294360492, 3622]]
1219
[[2265.756873777156, 5941]]
1220
[[1905.4206079111977, 2796]]
1229
[[1787.9974827168437, 6666]]
1232
[[1925.7742318119522, 1543]]
1239
[[2117.463178601505, 265], [2189.315426

In [84]:
6*196+9

1185

In [89]:
dist_dict[1199]

[[1987.277707528134, 7498],
 [1893.7310536679686, 7511],
 [1948.2169946358943, 7682]]

In [90]:
train_embeds = np.load('/home/hkhachatrian/mae/embeddings/fair1m/f1m_dino_8shot_embeds_train.npy', allow_pickle=True)

In [91]:
val_embeds = np.load('/home/hkhachatrian/mae/embeddings/fair1m/f1m_dino_8shot_embeds_val.npy', allow_pickle=True)

In [ ]:
train_embeds[16*196:17*196].shape

In [94]:
train_ind, val_ind = create_collage(train_annotation_file, val_annotation_file, images_folder)

In [95]:
train_ind

[38, 9, 10, 13, 15, 37]

In [96]:
val_ind

[37, 28, 2, 11, 15, 23]

In [114]:
train_selected_embedings = []
for ind in train_ind:
    train_selected_embedings.append(train_embeds[ind*196:(ind+1)*196])

In [103]:
train_selected_embedings[0]

array([[ 0.91988784, -1.3813585 ,  0.9070891 , ...,  3.581596  ,
        -1.7845345 , -0.8510629 ],
       [ 0.16895454,  0.20118722, -0.8524553 , ...,  2.1691465 ,
         0.30542234,  0.69526243],
       [ 2.162929  , -0.13780612, -0.7628146 , ..., -1.0606788 ,
        -3.4650576 ,  0.7065254 ],
       ...,
       [ 0.94605654,  0.1618266 , -2.5193615 , ..., -0.7451088 ,
         0.69466347,  0.01829228],
       [ 1.4090146 , -1.0346566 , -2.1495273 , ...,  1.0960224 ,
         0.524331  , -2.750167  ],
       [-2.9056056 , -1.9905461 , -1.0099107 , ..., -1.1566862 ,
         2.5306199 ,  1.5449716 ]], dtype=float32)

In [126]:
val_selected_embedings = []
for ind in val_ind:
    val_selected_embedings.append(val_embeds[ind*196:(ind+1)*196])

In [118]:
train_selected_embedings = torch.tensor(train_selected_embedings)
train_selected_embedings = train_selected_embedings.reshape(train_selected_embedings.shape[0]*train_selected_embedings.shape[1], train_selected_embedings.shape[2])

/tmp/ipykernel_2456572/3901525310.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_selected_embedings = torch.tensor(train_selected_embedings)


In [128]:
val_selected_embedings = torch.tensor(val_selected_embedings)
val_selected_embedings = val_selected_embedings.reshape(val_selected_embedings.shape[0]*val_selected_embedings.shape[1], val_selected_embedings.shape[2])

In [130]:
val_selected_embedings.shape

torch.Size([1176, 768])

In [119]:
train_selected_embedings.shape

torch.Size([1176, 768])

In [110]:
def cosine_distance_torch(x1, x2=None):
    x2 = x1 if x2 is None else x2
    return torch.mm(x1.to(float), x2.t().to(float))

In [132]:
dist_matrix = cosine_distance_torch(val_selected_embedings, train_selected_embedings)

In [133]:
dist_matrix.shape

torch.Size([1176, 1176])

In [134]:
train_embeds_dinov2 = np.load('../embeddings/fair1m/dinov2_250_8shot_embeds_train.npy', allow_pickle=True) #dinov2

In [136]:
train_embeds_dinov2[0:256]

array([[-0.39978427, -1.5718837 , -0.6731758 , ..., -0.46419984,
         1.1609342 , -1.1653557 ],
       [-1.6479429 ,  1.5179504 , -0.50437963, ..., -0.33668485,
         1.6940275 ,  2.7444398 ],
       [ 0.8331033 , -1.6844879 ,  1.7410773 , ..., -0.45694235,
         0.817243  , -0.28758106],
       ...,
       [ 2.238339  ,  0.5787894 ,  0.38942665, ...,  3.0340242 ,
        -0.6280305 ,  2.1370115 ],
       [ 0.79500306, -0.8774279 , -0.6781107 , ..., -0.10370152,
        -1.1099012 ,  1.3675096 ],
       [ 3.1607208 , -0.12138832, -2.3875456 , ..., -0.09764569,
        -2.065279  ,  2.3659184 ]], dtype=float32)